'use client';
import { useCallback, useEffect, useState } from 'react';

type Design = { id: string; name: string; version: number; document?: { elements?: { id: string; type: string; text?: string; color?: string; fontSize?: number; align?: string; x?: number; y?: number }[]; canvas?: { width: number; height: number }; theme?: { tokens?: { background?: string; primary?: string; font?: string } } } };
type Guest = { id: string; fullName: string; email?: string | null };
type Batch = { id: string; status: string; totalItems: number; completedItems: number; failedItems: number; items?: { id: string; guestId: string; status: string; objectKey: string | null; errorCode?: string | null }[]; createdAt: string };
async function api<T>(eventId: string, path: string, method = 'GET', data?: unknown, key?: string): Promise<T> {
  const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/${path}`, { method, headers: { ...(data !== undefined ? { 'content-type': 'application/json' } : {}), ...(key ? { 'idempotency-key': key } : {}) }, ...(data !== undefined ? { body: JSON.stringify(data) } : {}), cache: 'no-store' });
  const value = await response.json().catch(() => ({})); if (!response.ok) throw new Error(value?.message ?? 'La demande a échoué.'); return value as T;
}
export function InvitationsWorkspace({ eventId, eventName }: { eventId: string; eventName: string }) {
  const [designs, setDesigns] = useState<Design[]>([]); const [previewDesign, setPreviewDesign] = useState<Design | null>(null); const [guests, setGuests] = useState<Guest[]>([]); const [selectedGuests, setSelectedGuests] = useState<string[]>([]); const [designId, setDesignId] = useState(''); const [batches, setBatches] = useState<Batch[]>([]); const [batchDetails, setBatchDetails] = useState<Record<string, Batch>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => {
    try {
      const [designResult, batchResult] = await Promise.all([api<{ items: Design[] }>(eventId, 'designs'), api<Batch[]>(eventId, 'invitations/batches')]);
      setDesigns(designResult.items ?? []); setBatches(Array.isArray(batchResult) ? batchResult : []);
      const selectedDesignId = designResult.items?.[0]?.id || ''; setDesignId(current => current || selectedDesignId);
      const found: Guest[] = []; let cursor = '';
      do { const page = await api<{ items: Guest[]; nextCursor: string | null }>(eventId, `guests?limit=100${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`); found.push(...(page.items ?? [])); cursor = page.nextCursor ?? ''; if (found.length > 5000) break; } while (cursor);
      setGuests(found);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Impossible de charger les données.'); }
  }, [eventId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (designId) void api<Design>(eventId, `designs/${designId}`).then(setPreviewDesign).catch(error => setMessage(error.message)); }, [eventId, designId]);
  useEffect(() => { const timer = window.setInterval(() => { void api<Batch[]>(eventId, 'invitations/batches').then(items => setBatches(Array.isArray(items) ? items : [])).catch(() => undefined); }, 5000); return () => window.clearInterval(timer); }, [eventId]);
  const previewGuest = guests.find(guest => guest.id === selectedGuests[0]) ?? guests[0];
  const createBatch = async () => { if (!designId) return; setBusy(true); setMessage(''); try { const batch = await api<Batch>(eventId, 'invitations/batches', 'POST', { designId, ...(selectedGuests.length && selectedGuests.length < guests.length ? { guestIds: selectedGuests } : {}) }, crypto.randomUUID()); setBatches(items => [batch, ...items]); setSelectedGuests([]); setMessage('Le lot est en file de rendu.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Le lot n’a pas pu être créé.'); } finally { setBusy(false); } };
  const toggleGuest = (id: string) => setSelectedGuests(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  return <section className="invitation-workspace">
    <div className="invitation-panel"><div className="invitation-panel-title"><div><span className="eyebrow">PRÉPARATION</span><h2>Créer un lot PDF</h2></div><a href={`/events/${eventId}/designs`}>Gérer les designs ↗</a></div>
      {designs.length ? <label className="invitation-select">Design<select value={designId} onChange={e => setDesignId(e.target.value)}>{designs.map(d => <option value={d.id} key={d.id}>{d.name} · version {d.version}</option>)}</select></label> : <p className="invitation-empty">Créez d’abord un design pour préparer vos invitations.</p>}
      {previewDesign && <div className="invitation-preview" style={{ background: previewDesign.document?.theme?.tokens?.background ?? '#fbf7ef', color: previewDesign.document?.theme?.tokens?.primary ?? '#493a2a', fontFamily: previewDesign.document?.theme?.tokens?.font ?? 'Georgia,serif' }}><small>APERÇU PERSONNALISÉ · {previewGuest?.fullName ?? 'Invité'}</small><strong>{previewDesign.name}</strong>{(previewDesign.document?.elements ?? []).filter(layer => layer.type === 'TEXT' && layer.text).slice(0, 4).map(layer => <span key={layer.id}>{layer.text?.replace(/\{\{\s*(guest\.(?:name|fullName))\s*\}\}/gi, previewGuest?.fullName ?? 'Invité').replace(/\{\{\s*event\.name\s*\}\}/gi, eventName)}</span>)}<span>{previewGuest?.email ?? ''}</span></div>}
      <div className="invitation-guest-head"><div><h3>Invités</h3><p>{selectedGuests.length ? `${selectedGuests.length} sélectionné(s)` : `${guests.length} chargé(s) · tous seront inclus`}</p></div><button className="invitation-link-button" onClick={() => setSelectedGuests(selectedGuests.length === guests.length ? [] : guests.map(g => g.id))}>{selectedGuests.length === guests.length ? 'Tout désélectionner' : 'Tout sélectionner'}</button></div>
      <div className="invitation-guest-list">{guests.map(guest => <label key={guest.id}><input type="checkbox" checked={selectedGuests.includes(guest.id)} onChange={() => toggleGuest(guest.id)} /><span>{guest.fullName}</span><small>{guest.email}</small></label>)}</div>
      <div className="invitation-actions"><span>Coût estimé : {selectedGuests.length || guests.length} crédit(s)</span><button className="invitation-primary" disabled={busy || !designId || !guests.length} onClick={() => void createBatch()}>{busy ? 'Création…' : 'Générer les invitations'}</button></div>
      {message && <p className="invitation-message" role="status">{message}</p>}
    </div>
    <div className="invitation-panel"><div className="invitation-panel-title"><div><span className="eyebrow">RENDU ASYNCHRONE</span><h2>Lots récents</h2></div><button className="invitation-link-button" onClick={() => void load()}>Actualiser</button></div>
      {batches.length ? <div className="invitation-batches">{batches.map(batch => { const detail = batchDetails[batch.id]; return <article key={batch.id}><div><strong>{new Date(batch.createdAt).toLocaleString('fr-FR')}</strong><span className={`invitation-status ${batch.status.toLowerCase()}`}>{batch.status}</span></div><p>{batch.completedItems}/{batch.totalItems} PDF prêts{batch.failedItems ? ` · ${batch.failedItems} en échec` : ''}</p><div className="invitation-progress"><span style={{ width: `${batch.totalItems ? Math.min(100, batch.completedItems / batch.totalItems * 100) : 0}%` }} /></div><div className="invitation-actions">{batch.status === 'COMPLETED' && <a className="invitation-download" href={`/api/events/${eventId}/invitations/batches/${batch.id}/download`}>Télécharger le ZIP</a>}{<button className="invitation-link-button" onClick={() => detail ? setBatchDetails(current => { const next = { ...current }; delete next[batch.id]; return next; }) : void api<Batch>(eventId, `invitations/batches/${batch.id}`).then(value => setBatchDetails(current => ({ ...current, [batch.id]: value }))).catch(error => setMessage(error.message))}>{detail ? 'Masquer les PDF' : 'Voir les PDF'}</button>}{(detail?.items ?? []).filter(item => item.status === 'GENERATED').map(item => <a key={item.id} className="invitation-download" href={`/api/events/${eventId}/invitations/batches/${batch.id}/items/${item.id}/download`}>PDF {item.guestId.slice(0, 8)}</a>)}{['QUEUED','GENERATING','RESERVING'].includes(batch.status) && <button className="invitation-link-button" onClick={() => void api<Batch>(eventId, `invitations/batches/${batch.id}/cancel`, 'POST', {}).then(value => setBatchDetails(current => ({ ...current, [batch.id]: value }))).then(load).catch(error => setMessage(error.message))}>Annuler</button>}</div></article>; })}</div> : <p className="invitation-empty">Aucun lot créé pour cet événement.</p>}
    </div>
  </section>;
}
