import { decodeJwt } from 'jose';
import { revalidatePath } from 'next/cache';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getSession, sessionCookieName } from '@/lib/auth-session';

export const dynamic = 'force-dynamic';
type StorageStats = {
  disk: { diskStatsAvailable: boolean; totalBytes: number | null; usedBytes: number | null; freeBytes: number | null; percentage: number | null; level: string; thresholds: { warning: number; serious: number; critical: number; emergency: number } };
  application: { totalUsedBytes: number; totalFileCount: number; breakdownByCategory: Record<string, { bytes: number; count: number }>; breakdownByEvent: unknown[] | null; breakdownByAgency: unknown[] | null; largestFiles: Array<{ id: string; originalName: string; category: string; sizeBytes: number; createdAt: string }> };
  inventory: { lastAttemptAt: string | null; lastAttemptStatus: string | null; lastErrorCode: string | null; running: boolean };
  invitations: null | { measuredAt: string; pdf: { bytes: number | null; count: number; unknownSizeCount: number }; zip: { bytes: number | null; count: number; unknownSizeCount: number }; cleanup: { zipDeletionErrors: number; zipRetryable: number }; byEvent: Array<{ eventId: string; bytes: number | null; pdfCount: number | null; zipBytes: number | null; zipCount: number | null }>; byAgencyOrClient: Array<{ agencyWorkspaceId: string | null; ownerSubject: string; bytes: number | null; fileCount: number | null }> };
  cleanup: { deletedBytesLast24h: number; failures: number; referenceBlocked: number; pendingDeletion: number; lastRunAt: string | null; nextRunAt: string | null };
  minio: null | { status: string; measuredAt: string | null; validUntil: string | null; fresh: boolean; totalBytes: number | null; objectCount: number | null; summary: null | { complete?: boolean; buckets?: Record<string, { bytes: number | null; objectCount: number; complete: boolean }>; categories?: Record<string, { bytes: number; count: number }> | null; reconciliation?: { mediaMetadataObjectsMissingInMinio: number; mediaObjectsWithoutMetadata: number; mediaMetadataMissingSamples: string[]; mediaOrphanSamples: string[]; invitationMetadataAvailable: boolean; invitationMetadataObjectsMissingInMinio: number | null; invitationObjectsWithoutMetadata: number | null; expiredZipObjectsPresent: number | null; unknownInvitationZipSizeCount: number | null; expiredPreviewCandidateCount: number; deletionAutomatic: boolean } } };
};

const bytes = (value: number | null) => value === null ? 'Indisponible' : `${(value / 1024 ** 3).toFixed(2)} Go`;
const date = (value: string | null) => value ? new Date(value).toLocaleString('fr-FR') : 'Aucune exécution enregistrée';

export default async function StorageAdminPage() {
  const store = await cookies();
  const session = await getSession(store.get(sessionCookieName())?.value);
  if (!session) redirect('/api/auth/login?returnTo=%2Fadmin%2Fstorage');
  let roles: string[] = [];
  try {
    const access = decodeJwt(session.accessToken)['realm_access'];
    roles = access && typeof access === 'object' && 'roles' in access && Array.isArray(access.roles) ? access.roles.filter((role): role is string => typeof role === 'string') : [];
  } catch { /* API verifies the signed token again. */ }
  if (!roles.some((role) => role === 'SUPER_ADMIN' || role === 'SUPPORT_ADMIN')) return <main className="admin-shell"><a href="/admin">← Administration</a><section className="admin-denied"><span>ACCÈS RESTREINT</span><h1>Permission d’administration requise</h1><p>Le stockage est réservé aux rôles Support Admin et Super Admin.</p></section></main>;

  async function refreshInventory() {
    'use server';
    const jar = await cookies();
    const current = await getSession(jar.get(sessionCookieName())?.value);
    if (!current) redirect('/api/auth/login?returnTo=%2Fadmin%2Fstorage');
    await fetch(`${process.env['GATEWAY_INTERNAL_URL'] ?? 'http://gateway:3002'}/v1/admin/storage/refresh`, { method: 'POST', headers: { authorization: `Bearer ${current.accessToken}` }, cache: 'no-store', signal: AbortSignal.timeout(120_000) }).catch(() => undefined);
    revalidatePath('/admin/storage');
  }

  let data: StorageStats | null = null;
  try {
    const response = await fetch(`${process.env['GATEWAY_INTERNAL_URL'] ?? 'http://gateway:3002'}/v1/admin/storage`, { headers: { authorization: `Bearer ${session.accessToken}` }, cache: 'no-store', signal: AbortSignal.timeout(8000) });
    if (response.ok) data = await response.json() as StorageStats;
  } catch { /* Show an unavailable state without inventing metrics. */ }

  const categories = [
    ['Originaux', 'originals'], ['PNG dérivés', 'derived'], ['Previews', 'previews'], ['PDF finaux', 'pdfFinal'], ['ZIP', 'zip'], ['Temporaires', 'temp'],
  ] as const;
  return <main className="admin-shell">
    <header><span>INVITAFLOW · STOCKAGE</span><h1>Capacité et fichiers</h1><p>Les chiffres applicatifs viennent des assets Media prêts. L’espace disque est lu sur le volume MinIO lorsqu’il est monté et accessible.</p></header>
    {!data ? <section className="admin-panel"><h2>Mesures indisponibles</h2><p>Le service Media n’a pas répondu. Aucune valeur n’est simulée.</p></section> : <>
      <section className="admin-panel"><div className="admin-panel-head"><div><small>CAPACITÉ FILESYSTEM DU VOLUME MONTÉ</small><h2>{data.disk.diskStatsAvailable ? `${bytes(data.disk.usedBytes)} / ${bytes(data.disk.totalBytes)}` : 'Mesure disque indisponible'}</h2></div><span>{data.disk.percentage === null ? '—' : `${data.disk.percentage.toFixed(1)} % · ${data.disk.level}`}</span></div><p>{data.disk.diskStatsAvailable ? `${bytes(data.disk.freeBytes)} libres` : 'Le chemin du volume n’est pas monté ou statfs est indisponible.'}</p><p>Cette capacité système ne représente pas le total exact des objets/buckets MinIO. Seuils filesystem : warning {data.disk.thresholds.warning} %, sérieux {data.disk.thresholds.serious} %, critique {data.disk.thresholds.critical} %, urgence {data.disk.thresholds.emergency} %.</p></section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>INVENTAIRE MINIO · OBJETS S3 RÉELS</small><h2>{data.minio?.status === 'COMPLETE' ? bytes(data.minio.totalBytes) : data.minio?.status === 'INCOMPLETE' ? 'Inventaire incomplet' : 'Aucun inventaire'}</h2></div><form action={refreshInventory}><button className="admin-next" type="submit" disabled={data.inventory.running}>Actualiser l’inventaire</button></form></div><p>Dernière mesure : {date(data.minio?.measuredAt ?? null)} · valide jusqu’au : {date(data.minio?.validUntil ?? null)} · {data.minio?.fresh ? 'à jour' : 'périmé ou incomplet'}</p><p>{data.minio?.objectCount ?? '—'} objets listés · dernière tentative : {data.inventory.lastAttemptStatus ?? 'aucune'} {data.inventory.lastErrorCode ? `(${data.inventory.lastErrorCode})` : ''}</p>{data.minio?.summary?.buckets && <div className="admin-table-wrap"><table><thead><tr><th>Bucket</th><th>Octets réels listés</th><th>Objets</th><th>Complet</th></tr></thead><tbody>{Object.entries(data.minio.summary.buckets).map(([bucket, row]) => <tr key={bucket}><td>{bucket}</td><td>{bytes(row.bytes)}</td><td>{row.objectCount}</td><td>{row.complete ? 'Oui' : 'Non'}</td></tr>)}</tbody></table></div>}{data.minio?.summary?.categories && <p>Par catégorie réelle : originaux {bytes(data.minio.summary.categories['originals']?.bytes ?? null)} · dérivés {bytes(data.minio.summary.categories['derived']?.bytes ?? null)} · previews/miniatures {bytes(data.minio.summary.categories['previews']?.bytes ?? null)} · PDF {bytes(data.minio.summary.categories['pdfFinal']?.bytes ?? null)} · ZIP {bytes(data.minio.summary.categories['zip']?.bytes ?? null)} · temporaires {bytes(data.minio.summary.categories['temp']?.bytes ?? null)} · générés non classés {bytes(data.minio.summary.categories['generatedUnclassified']?.bytes ?? null)}.</p>}{data.minio?.summary?.reconciliation && <><p>Media : métadonnées sans objet {data.minio.summary.reconciliation.mediaMetadataObjectsMissingInMinio} · objets sans métadonnées {data.minio.summary.reconciliation.mediaObjectsWithoutMetadata} · previews candidates à expiration {data.minio.summary.reconciliation.expiredPreviewCandidateCount}.</p><p>Invitations : vérification metadata {data.minio.summary.reconciliation.invitationMetadataAvailable ? 'disponible' : 'inconnue'} · PDF/ZIP metadata sans objet {data.minio.summary.reconciliation.invitationMetadataObjectsMissingInMinio ?? '—'} · objets PDF/ZIP sans metadata {data.minio.summary.reconciliation.invitationObjectsWithoutMetadata ?? '—'} · ZIP expirés présents {data.minio.summary.reconciliation.expiredZipObjectsPresent ?? '—'} · tailles ZIP historiques inconnues {data.minio.summary.reconciliation.unknownInvitationZipSizeCount ?? '—'}.</p><p>Les objets ambigus ne sont jamais supprimés automatiquement.</p></>}</section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>STOCKAGE APPLICATIF · TOTAL DES TAILLES CONNUES</small><h2>{bytes(data.application.totalUsedBytes + (data.invitations?.pdf.bytes ?? 0) + (data.invitations?.zip.bytes ?? 0))}</h2></div><span>{data.application.totalFileCount + (data.invitations?.pdf.count ?? 0) + (data.invitations?.zip.count ?? 0)} fichier(s) suivis</span></div><div className="admin-table-wrap"><table><thead><tr><th>Catégorie</th><th>Volume connu</th><th>Fichiers</th></tr></thead><tbody>{categories.map(([label, key]) => { const media = data.application.breakdownByCategory[key]; const invitation = key === 'pdfFinal' ? data.invitations?.pdf : key === 'zip' ? data.invitations?.zip : null; return <tr key={key}><td>{label}</td><td>{key === 'temp' ? 'Indisponible' : invitation ? bytes(invitation.bytes) : key === 'pdfFinal' || key === 'zip' ? 'Indisponible' : bytes(media?.bytes ?? null)}</td><td>{key === 'temp' ? '—' : invitation ? invitation.count : key === 'pdfFinal' || key === 'zip' ? '—' : media?.count ?? '—'}</td></tr>; })}</tbody></table></div><p>Les tailles historiques inconnues restent exclues des sommes et sont comptées à part. Les fichiers temporaires ne sont pas encore inventoriés de façon exhaustive.</p>{data.invitations && <p>PDF à taille inconnue : {data.invitations.pdf.unknownSizeCount} · ZIP à taille inconnue : {data.invitations.zip.unknownSizeCount}</p>}</section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>TOP ÉVÉNEMENTS</small><h2>Consommation Invitations</h2></div></div>{data.invitations?.byEvent.length ? <div className="admin-table-wrap"><table><thead><tr><th>Événement</th><th>PDF mesurés</th><th>ZIP actifs</th><th>Volume connu</th></tr></thead><tbody>{data.invitations.byEvent.map((row) => <tr key={row.eventId}><td>{row.eventId}</td><td>{row.pdfCount ?? '—'}</td><td>{row.zipCount ?? '—'}</td><td>{bytes(row.bytes === null || row.zipBytes === null && row.zipCount ? null : (row.bytes ?? 0) + (row.zipBytes ?? 0))}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucune consommation événement mesurée.</p>}</section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>TOP AGENCES / CLIENTS</small><h2>Consommation Invitations</h2></div></div>{data.invitations?.byAgencyOrClient.length ? <div className="admin-table-wrap"><table><thead><tr><th>Agence</th><th>Propriétaire</th><th>Fichiers</th><th>Volume connu</th></tr></thead><tbody>{data.invitations.byAgencyOrClient.map((row) => <tr key={`${row.agencyWorkspaceId ?? 'client'}:${row.ownerSubject}`}><td>{row.agencyWorkspaceId ?? 'Client direct'}</td><td>{row.ownerSubject}</td><td>{row.fileCount ?? '—'}</td><td>{bytes(row.bytes)}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucune consommation agence/client mesurée.</p>}<p>Ce relevé couvre les PDF/ZIP et les lots identifiés dans Invitations. Les assets Media n’ont pas encore de référence d’événement/agence consolidée.</p></section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>NETTOYAGE</small><h2>{bytes(data.cleanup.deletedBytesLast24h)} supprimés sur 24 h</h2></div><span>{data.cleanup.failures + (data.invitations?.cleanup.zipDeletionErrors ?? 0)} échec(s) suivis</span></div><p>Dernière exécution : {date(data.cleanup.lastRunAt)} · prochaine : {date(data.cleanup.nextRunAt)}</p><p>Suppressions Media en attente : {data.cleanup.pendingDeletion} · vérifications bloquées par une référence : {data.cleanup.referenceBlocked}</p>{data.invitations && <p>ZIP expirés en attente de retry : {data.invitations.cleanup.zipRetryable}</p>}</section>
      <section className="admin-panel" style={{ marginTop: 18 }}><div className="admin-panel-head"><div><small>FICHIERS</small><h2>Les plus volumineux</h2></div></div>{data.application.largestFiles.length ? <div className="admin-table-wrap"><table><thead><tr><th>Nom</th><th>Catégorie</th><th>Taille</th><th>Créé</th></tr></thead><tbody>{data.application.largestFiles.map((file) => <tr key={file.id}><td>{file.originalName}</td><td>{file.category}</td><td>{bytes(file.sizeBytes)}</td><td>{new Date(file.createdAt).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucun fichier prêt.</p>}</section>
    </>}
  </main>;
}
