'use client';

import { useMemo, useState, type FormEvent } from 'react';

type Partner = { id: string; ownerSubject: string | null; code: string; status: string; commissionRateBps: number; eligibleOrderTypes: string[]; _count?: { attributions: number; ledgerEntries: number; payouts: number } };
type Ledger = { id: string; partnerId: string; paymentId: string; orderType: string; baseAmountMinor: number; commissionAmountMinor: number; rateBpsSnapshot: number; currency: string; status: string; createdAt: string; partner?: { code: string } };
type Payout = { id: string; partnerId: string; amountMinor: number; currency: string; status: string; externalReference: string | null; partner?: { code: string } };
type Attribution = { id: string; customerSubject: string; source: string; codeSnapshot: string; status: string; attributedAt: string; partner?: { code: string } };
type AuditEntry = { id: string; actorSubject: string; action: string; before: unknown; after: unknown; createdAt: string; partner?: { code: string } };
async function request(path: string, method = 'GET', data?: Record<string, unknown>) {
  const response = await fetch(`/api/admin/partners${path}`, { method, ...(data ? { headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) } : {}), cache: 'no-store' });
  const value: unknown = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(value && typeof value === 'object' && 'message' in value && typeof value.message === 'string' ? value.message : 'La requête a échoué.');
  return value;
}

export function PartnerAdminConsole({ initialPartners, initialLedger, initialPayouts, initialAttributions, initialAudit }: { initialPartners: Partner[]; initialLedger: Ledger[]; initialPayouts: Payout[]; initialAttributions: Attribution[]; initialAudit: AuditEntry[] }) {
  const [partners, setPartners] = useState(initialPartners); const [ledger, setLedger] = useState(initialLedger); const [payouts, setPayouts] = useState(initialPayouts);
  const [attributions, setAttributions] = useState(initialAttributions);
  const [audit, setAudit] = useState(initialAudit);
  const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const filtered = useMemo(() => partners.filter((partner) => `${partner.code} ${partner.ownerSubject ?? ''} ${partner.status}`.toLowerCase().includes(search.toLowerCase())), [partners, search]);
  async function refresh() { const [p, l, o, a, h] = await Promise.all([request(''), request('/ledger'), request('/payouts'), request('/attributions'), request('/audit')]); setPartners(p as Partner[]); setLedger(l as Ledger[]); setPayouts(o as Payout[]); setAttributions(a as Attribution[]); setAudit(h as AuditEntry[]); }
  async function act(operation: () => Promise<unknown>) { setBusy(true); setError(''); try { await operation(); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erreur inconnue.'); } finally { setBusy(false); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act(() => request('', 'POST', { code: form.get('code'), ownerSubject: form.get('ownerSubject') || null, commissionRateBps: Number(form.get('rate')), eligibleOrderTypes: form.getAll('eligible').map(String) })); event.currentTarget.reset(); }
  return <>
    {error && <p className="partner-admin-error" role="alert">{error}</p>}
    <section className="admin-panel"><h2>Créer un partenaire</h2><form className="partner-admin-form" onSubmit={create}><label>Code<input name="code" required pattern="[A-Za-z0-9_-]{3,60}"/></label><label>Compte propriétaire<input name="ownerSubject" maxLength={255}/></label><label>Taux (points de base)<input name="rate" type="number" min="0" max="10000" required/></label><fieldset><legend>Commandes éligibles</legend><label><input type="checkbox" name="eligible" value="CREDIT_PURCHASE"/> Achat de crédits</label><label><input type="checkbox" name="eligible" value="AGENCY_SUBSCRIPTION"/> Abonnement agence</label></fieldset><button disabled={busy}>Créer</button></form></section>
    <section className="admin-panel"><div className="partner-admin-title"><h2>Partenaires</h2><input aria-label="Rechercher un partenaire" placeholder="Rechercher code, compte, statut" value={search} onChange={(event) => setSearch(event.target.value)}/></div>{filtered.length ? <div className="admin-table-wrap"><table><thead><tr><th>Code</th><th>Compte</th><th>Taux bps</th><th>Éligibilité</th><th>Attributions</th><th>Statut</th></tr></thead><tbody>{filtered.map((partner) => <tr key={partner.id}><td>{partner.code}</td><td><input aria-label={`Compte ${partner.code}`} defaultValue={partner.ownerSubject ?? ''} placeholder="subject Keycloak" disabled={busy} onBlur={(event) => { const value = event.currentTarget.value.trim() || null; if (value !== partner.ownerSubject) void act(() => request(`/${partner.id}`, 'PATCH', { ownerSubject: value })); }}/></td><td><input aria-label={`Taux ${partner.code}`} type="number" min="0" max="10000" defaultValue={partner.commissionRateBps} disabled={busy} onBlur={(event) => { const value = Number(event.currentTarget.value); if (value !== partner.commissionRateBps) void act(() => request(`/${partner.id}`, 'PATCH', { commissionRateBps: value })); }}/></td><td><select aria-label={`Commandes éligibles ${partner.code}`} multiple value={partner.eligibleOrderTypes} disabled={busy} onChange={(event) => void act(() => request(`/${partner.id}`, 'PATCH', { eligibleOrderTypes: Array.from(event.currentTarget.selectedOptions, (option) => option.value) }))}><option value="CREDIT_PURCHASE">Achat crédits</option><option value="AGENCY_SUBSCRIPTION">Abonnement agence</option></select></td><td>{partner._count?.attributions ?? 0}</td><td><select value={partner.status} disabled={busy} onChange={(event) => void act(() => request(`/${partner.id}`, 'PATCH', { status: event.target.value }))}><option>PENDING</option><option>ACTIVE</option><option>SUSPENDED</option></select></td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucun partenaire enregistré.</p>}</section>
    <section className="admin-panel"><h2>Commissions</h2>{ledger.length ? <div className="admin-table-wrap"><table><thead><tr><th>Partenaire</th><th>Paiement</th><th>Base</th><th>Taux</th><th>Montant</th><th>Statut/action</th></tr></thead><tbody>{ledger.map((entry) => <tr key={entry.id}><td>{entry.partner?.code ?? entry.partnerId}</td><td>{entry.paymentId}</td><td>{(entry.baseAmountMinor / 100).toLocaleString('fr-FR')} {entry.currency}</td><td>{(entry.rateBpsSnapshot / 100).toLocaleString('fr-FR')}%</td><td>{(entry.commissionAmountMinor / 100).toLocaleString('fr-FR')} {entry.currency}</td><td>{entry.status}{entry.status === 'PENDING' && <button disabled={busy} onClick={() => void act(() => request(`/ledger/${entry.id}`, 'PATCH', { status: 'VALIDATED' }))}>Valider</button>}{entry.status === 'VALIDATED' && <button disabled={busy} onClick={() => void act(() => request(`/ledger/${entry.id}`, 'PATCH', { status: 'PAYABLE' }))}>Rendre payable</button>}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucune commission dans le ledger.</p>}</section>
    <section className="admin-panel"><h2>Attributions</h2>{attributions.length ? <div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Client</th><th>Partenaire</th><th>Source/code</th><th>État</th></tr></thead><tbody>{attributions.map((item) => <tr key={item.id}><td>{new Date(item.attributedAt).toLocaleDateString('fr-FR')}</td><td>{item.customerSubject}</td><td>{item.partner?.code ?? '—'}</td><td>{item.source} · {item.codeSnapshot}</td><td>{item.status}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucune attribution enregistrée.</p>}</section>
    <section className="admin-panel"><h2>Payouts</h2>{payouts.length ? <div className="admin-table-wrap"><table><thead><tr><th>Partenaire</th><th>Montant</th><th>Statut</th><th>Référence</th><th>Action</th></tr></thead><tbody>{payouts.map((payout) => <tr key={payout.id}><td>{payout.partner?.code ?? payout.partnerId}</td><td>{(payout.amountMinor / 100).toLocaleString('fr-FR')} {payout.currency}</td><td>{payout.status}</td><td>{payout.externalReference ?? '—'}</td><td>{payout.status === 'PENDING' && <button disabled={busy} onClick={() => void act(() => request(`/payouts/${payout.id}`, 'PATCH', { status: 'APPROVED' }))}>Approuver</button>}{payout.status === 'APPROVED' && <button disabled={busy} onClick={() => void act(() => request(`/payouts/${payout.id}`, 'PATCH', { status: 'PROCESSING' }))}>En traitement</button>}{payout.status === 'PROCESSING' && <span>En attente du connecteur de paiement externe</span>}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucun payout.</p>}<p>La confirmation PAID reste bloquée tant qu’un fournisseur ne renvoie pas une confirmation vérifiable.</p></section>
    <section className="admin-panel"><h2>Journal d’audit</h2>{audit.length ? <div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Partenaire</th><th>Action</th><th>Acteur</th></tr></thead><tbody>{audit.map((entry) => <tr key={entry.id}><td>{new Date(entry.createdAt).toLocaleString('fr-FR')}</td><td>{entry.partner?.code ?? '—'}</td><td>{entry.action}</td><td>{entry.actorSubject}</td></tr>)}</tbody></table></div> : <p className="admin-empty">Aucune action d’administration enregistrée.</p>}</section>
  </>;
}
