'use client';
import { useEffect, useRef, useState } from 'react';

type Ceremony = { id: string; name: string; startAt?: string };
type ScanResult = { alreadyCheckedIn: boolean; guestName: string; checkedAt: string; companionCount: number; allowedCompanions: number };
type BarcodeDetectorLike = { detect(source: HTMLVideoElement): Promise<{ rawValue: string }[]> };
type CameraWindow = Window & { BarcodeDetector?: new (options?: { formats: string[] }) => BarcodeDetectorLike };
export function CheckInWorkspace({ eventId, ceremonies, isOwner }: { eventId: string; ceremonies: Ceremony[]; isOwner: boolean }) {
  const [ceremonyId, setCeremonyId] = useState(ceremonies[0]?.id ?? ''); const [token, setToken] = useState(''); const [companions, setCompanions] = useState(0); const [companionLimit, setCompanionLimit] = useState(0); const [scan, setScan] = useState<ScanResult | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [camera, setCamera] = useState(false); const [summary, setSummary] = useState<{ checkedIn: number; accepted: number; recent: { guestName: string; checkedAt: string; companionCount: number }[] } | null>(null);
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null);
  const refresh = async () => { if (!ceremonyId) return; try { const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/check-in?ceremonyId=${encodeURIComponent(ceremonyId)}`, { cache: 'no-store' }); if (response.ok) setSummary(await response.json()); } catch { /* The scanner remains usable while the summary refreshes. */ } };
  useEffect(() => { void refresh(); }, [eventId, ceremonyId]);
  useEffect(() => { const candidate = token.trim().match(/(?:\/invite\/)?([0-9a-f-]{36}\.[A-Za-z0-9_-]{43})/i)?.[1]; if (!candidate) { setCompanionLimit(0); setCompanions(0); return; } let active = true; fetch(`/api/public/invitations/${encodeURIComponent(candidate)}`, { cache: 'no-store', referrerPolicy: 'no-referrer' }).then(response => response.ok ? response.json() : null).then((invite: { ceremonies?: { id: string; allowedCompanions: number }[] } | null) => { if (!active) return; const limit = invite?.ceremonies?.find(item => item.id === ceremonyId)?.allowedCompanions ?? 0; setCompanionLimit(limit); setCompanions(value => Math.min(value, limit)); }).catch(() => { if (active) { setCompanionLimit(0); setCompanions(0); } }); return () => { active = false; }; }, [token, ceremonyId]);
  useEffect(() => { let active = true; let timer: number | undefined; const start = async () => { if (!camera || !video.current) return; const Detector = (window as CameraWindow).BarcodeDetector; if (!Detector) { setMessage('Le scan caméra n’est pas pris en charge par ce navigateur. Saisissez le code manuellement.'); setCamera(false); return; } try { stream.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); video.current.srcObject = stream.current; await video.current.play(); const detector = new Detector({ formats: ['qr_code'] }); const loop = async () => { if (!active || !video.current) return; try { const codes = await detector.detect(video.current); if (codes[0]?.rawValue) { setToken(codes[0].rawValue); setCamera(false); return; } } catch { /* wait for the next camera frame */ } timer = window.setTimeout(() => void loop(), 300); }; void loop(); } catch { setMessage('Accès à la caméra refusé ou indisponible. Saisissez le code manuellement.'); setCamera(false); } }; void start(); return () => { active = false; if (timer) window.clearTimeout(timer); stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; }; }, [camera]);
  const submit = async (value = token) => { if (!ceremonyId || !value.trim()) return; const candidate = value.trim().match(/(?:\/invite\/)?([0-9a-f-]{36}\.[A-Za-z0-9_-]{43})/i)?.[1]; if (!candidate) { setMessage('Ce code QR ne correspond pas à une invitation InvitaFlow.'); return; } setBusy(true); setMessage(''); setScan(null); try { const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/check-in/scan`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-checkin-device-id': getDeviceId() }, body: JSON.stringify({ token: candidate, ceremonyId, companionCount: companions }), cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'Pointage refusé.'); setScan(result); setCompanions(0); setToken(''); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Le pointage a échoué.'); } finally { setBusy(false); } };
  return <><div className="check-grid"><section className="check-card"><label>Cérémonie<select value={ceremonyId} onChange={event => setCeremonyId(event.target.value)}>{ceremonies.map(ceremony => <option key={ceremony.id} value={ceremony.id}>{ceremony.name}</option>)}</select></label>{!ceremonies.length && <p>Aucune cérémonie n’est définie pour cet événement.</p>}<div className="check-camera">{camera && <video ref={video} muted playsInline />}</div><button className="check-secondary" disabled={!ceremonyId || busy} onClick={() => { setMessage(''); setCamera(value => !value); }}>{camera ? 'Arrêter la caméra' : 'Scanner avec la caméra'}</button><label>Code ou lien de l’invitation<input value={token} onChange={event => setToken(event.target.value)} placeholder="Collez ou scannez le QR code" autoComplete="off" /></label><label>Accompagnants présents<select value={companions} onChange={event => setCompanions(Number(event.target.value))}>{Array.from({ length: companionLimit + 1 }, (_, i) => <option value={i} key={i}>{i}</option>)}</select></label><button className="check-primary" disabled={!ceremonyId || busy || !token.trim()} onClick={() => void submit()}>{busy ? 'Vérification…' : 'Valider l’entrée'}</button>{scan && <div className={`check-result ${scan.alreadyCheckedIn ? 'duplicate' : ''}`} role="status"><strong>{scan.alreadyCheckedIn ? 'Déjà pointé' : 'Présence enregistrée'}</strong><span>{scan.guestName}</span><small>{new Date(scan.checkedAt).toLocaleTimeString('fr-FR')} · {scan.companionCount} accompagnant(s)</small></div>}{message && <p className="check-message" role="status">{message}</p>}</section><section className="check-card"><p className="check-eyebrow">SUIVI EN DIRECT</p><h2>{summary?.checkedIn ?? 0} entrée(s) enregistrée(s)</h2><p>{summary?.accepted ?? 0} réponse(s) positive(s) au RSVP</p><button className="check-secondary" onClick={() => void refresh()}>Actualiser</button><div className="check-recent">{summary?.recent.map((item, index) => <article key={`${item.checkedAt}-${index}`}><strong>{item.guestName}</strong><span>{new Date(item.checkedAt).toLocaleTimeString('fr-FR')} · {item.companionCount} accompagnant(s)</span></article>)}</div></section></div>{isOwner && <AgentManager eventId={eventId} ceremonies={ceremonies} />}</>;
}

function AgentManager({ eventId, ceremonies }: { eventId: string; ceremonies: Ceremony[] }) {
  const [subject, setSubject] = useState('');
  const [selected, setSelected] = useState<string[]>(ceremonies.map(item => item.id));
  const [agents, setAgents] = useState<{ agentSubject: string; status: string; ceremonies: { ceremonyId: string }[] }[]>([]);
  const [error, setError] = useState('');
  const load = async () => { const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/access-agents`, { cache: 'no-store' }); if (response.ok) setAgents((await response.json()).items ?? []); };
  useEffect(() => { void load(); }, [eventId]);
  const save = async () => {
    setError('');
    if (!subject.trim() || !selected.length) { setError('Indiquez le sujet Keycloak de l’agent et au moins une cérémonie.'); return; }
    const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/access-agents/${encodeURIComponent(subject.trim())}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ceremonyIds: selected }) });
    if (!response.ok) { const body = await response.json().catch(() => null); setError(body?.message ?? 'L’affectation a échoué.'); return; }
    setSubject(''); await load();
  };
  const revoke = async (agentSubject: string) => {
    const response = await fetch(`/api/events/${encodeURIComponent(eventId)}/access-agents/${encodeURIComponent(agentSubject)}`, { method: 'DELETE' });
    if (!response.ok) { setError('La révocation a échoué.'); return; }
    await load();
  };
  return <section className="check-card agent-manager"><p className="check-eyebrow">ÉQUIPE DE POINTAGE</p><h2>Agents autorisés</h2><p>Ajoutez le sujet de compte Keycloak de chaque agent et limitez-le aux cérémonies nécessaires.</p><label>Sujet Keycloak de l’agent<input value={subject} onChange={event => setSubject(event.target.value)} autoComplete="off" /></label><fieldset><legend>Cérémonies accessibles</legend>{ceremonies.map(item => <label className="agent-check" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} />{item.name}</label>)}</fieldset><button className="check-primary" onClick={() => void save()}>Enregistrer l’agent</button>{error && <p className="check-message" role="status">{error}</p>}<div className="check-recent">{agents.map(agent => <article key={agent.agentSubject}><strong>{agent.agentSubject}</strong><span>{agent.status} · {agent.ceremonies.length} cérémonie(s)</span>{agent.status === 'ACTIVE' && <button className="check-secondary" onClick={() => void revoke(agent.agentSubject)}>Révoquer</button>}</article>)}</div></section>;
}

function getDeviceId() {
  if (typeof window === 'undefined') return '';
  const key = 'invitaflow.checkin.device-id';
  let value = window.localStorage.getItem(key);
  if (!value) { value = window.crypto.randomUUID(); window.localStorage.setItem(key, value); }
  return value;
}
