stateDiagram-v2
    title: Machine paiement
    [*] --> CREATED
    CREATED --> PROCESSING
    CREATED --> CANCELLED
    PROCESSING --> PENDING
    PROCESSING --> CREATED
    PENDING --> PROCESSING
    PENDING --> SUCCEEDED
    PENDING --> FAILED
    PENDING --> CANCELLED
    PENDING --> EXPIRED
    PROCESSING --> SUCCEEDED
    PROCESSING --> FAILED
    PROCESSING --> CANCELLED
    PROCESSING --> EXPIRED
    SUCCEEDED --> REFUND_PENDING
    REFUND_PENDING --> REFUNDED
    REFUND_PENDING --> SUCCEEDED
    REFUNDED --> [*]
    FAILED --> [*]
    CANCELLED --> [*]
    EXPIRED --> [*]
