'use client';

import { useState, type FormEvent } from 'react';
import { agencyPeriod } from './agency-period.mjs';

export type AgencyPlan = { id: string; key: string; name: string; credits: number; periodDays?: number | null; priceMinor: number; currency: string; segment: string };
export type Agency = { id: string; name: string; status: string; role: 'OWNER' | 'ADMIN' | 'MEMBER'; plan: null | { planName: string; quotaCredits: number; priceMinor: number; currency: string; status: string; billingPeriodStart?: string | null; billingPeriodEnd?: string | null }; usage: { consumed: number; reserved: number }; clients: number; events: number };
type Client = { id: string; name: string; email: string | null; phone: string | null };
type Member = { id: string; subject: string; role: string; status: string };
type Event = { id: string; name: string; eventType: string; status: string; startAt: string | null; agencyClientEvents: Array<{ clientId: string }> };

async function api<T>(path = '', method = 'GET', data?: Record<string, unknown>): Promise<T> {
  const response = await fetch(`/api/agencies${path}`, { method, ...(data ? { headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) } : {}), cache: 'no-store' });
  const value: unknown = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(value && typeof value === 'object' && 'message' in value && typeof value.message === 'string' ? value.message : 'La requête agence a échoué.');
  return value as T;
}

export function AgencyWorkspace({ initialAgencies, plans }: { initialAgencies: Agency[]; plans: AgencyPlan[] }) {
  const [agencies, setAgencies] = useState(initialAgencies);
  const [selectedId, setSelectedId] = useState(initialAgencies[0]?.id ?? '');
  const [clients, setClients] = useState<Client[]>([]);
  const [members, setMembers] = useState<Member[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [selectedPlanKey, setSelectedPlanKey] = useState('');
  const current = agencies.find((agency) => agency.id === selectedId) ?? null;
  async function refresh(workspaceId = selectedId) {
    if (!workspaceId) return;
    const [nextClients, nextMembers, nextEvents] = await Promise.all([api<Client[]>(`/${workspaceId}/clients`), api<Member[]>(`/${workspaceId}/members`), api<Event[]>(`/${workspaceId}/events`)]);
    setClients(nextClients); setMembers(nextMembers); setEvents(nextEvents); setLoaded(true);
    setAgencies(await api<Agency[]>());
  }
  async function act(operation: () => Promise<void>) { setBusy(true); setMessage(''); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Une erreur est survenue.'); } finally { setBusy(false); } }
  async function createAgency(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('name') ?? ''); await act(async () => { const created = await api<Agency>('', 'POST', { name }); const next = await api<Agency[]>(); setAgencies(next); setSelectedId(created.id); await refresh(created.id); }); }
  async function createClient(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act(async () => { await api(`/${selectedId}/clients`, 'POST', { name: form.get('name'), email: form.get('email') || null, phone: form.get('phone') || null }); event.currentTarget.reset(); await refresh(); }); }
  async function createMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act(async () => { await api(`/${selectedId}/members`, 'POST', { subject: form.get('subject'), role: form.get('role') }); event.currentTarget.reset(); await refresh(); }); }
  async function updateMember(member: Member, change: { role?: string; status?: string }) { await act(async () => { await api(`/${selectedId}/members/${member.id}`, 'PATCH', change); await refresh(); }); }
  async function createEvent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const clientId = String(form.get('clientId') ?? ''); await act(async () => { await api(`/${selectedId}/events`, 'POST', { clientId, name: form.get('name'), eventType: form.get('eventType'), timezone: 'Africa/Kinshasa' }); event.currentTarget.reset(); await refresh(); }); }
  async function startCheckout() { const planKey = selectedPlanKey; if (!planKey) return; await act(async () => { const result = await api<{ payment?: { checkoutUrl?: string | null } }>(`/${selectedId}/subscriptions`, 'POST', { planKey }); await refresh(); if (result.payment?.checkoutUrl) window.location.assign(result.payment.checkoutUrl); else setMessage('Commande créée · en attente du lien de paiement.'); }); }
  return <section className="agency-content">
    {message && <p role="status" className="agency-feedback">{message}</p>}
    <div className="agency-toolbar"><label>Workspace<select value={selectedId} onChange={(event) => { setSelectedId(event.target.value); setLoaded(false); void refresh(event.target.value).catch((error) => setMessage(error.message)); }}><option value="">Choisir une agence</option>{agencies.map((agency) => <option key={agency.id} value={agency.id}>{agency.name}</option>)}</select></label><form onSubmit={createAgency}><input name="name" minLength={2} maxLength={120} required placeholder="Nom de l’agence"/><button disabled={busy}>Créer une agence</button></form></div>
    {!current ? <div className="agency-empty"><h2>Aucune agence</h2><p>Créez un workspace pour gérer vos clients et leurs événements.</p></div> : <>
      <section className="agency-overview"><div><small>ESPACE AGENCE</small><h2>{current.name}</h2><p>Rôle {current.role} · {current.status === 'ACTIVE' ? 'Actif' : 'Suspendu'}</p></div><div className="agency-metrics"><article><span>Plan actuel</span><strong>{current.plan?.planName ?? 'Aucun plan actif'}</strong><small>{current.plan ? `${current.plan.status === 'PAST_DUE' ? 'Expiré' : current.plan.status} · ${current.plan.priceMinor / 100} ${current.plan.currency}` : 'Sélectionnez un plan ci-dessous'}</small></article><article><span>Quota</span><strong>{(current.plan?.quotaCredits ?? 0).toLocaleString('fr-FR')} invitations</strong><small>{current.usage.consumed.toLocaleString('fr-FR')} utilisées · {current.usage.reserved.toLocaleString('fr-FR')} réservées · {Math.max(0, (current.plan?.quotaCredits ?? 0) - current.usage.consumed - current.usage.reserved).toLocaleString('fr-FR')} restantes</small></article><article><span>Clients</span><strong>{current.clients}</strong></article><article><span>Événements</span><strong>{current.events}</strong></article><article><span>Membres</span><strong>{members.length || '—'}</strong></article></div>{current.plan?.billingPeriodStart && current.plan.billingPeriodEnd && (() => { const period = agencyPeriod(current.plan.billingPeriodStart, current.plan.billingPeriodEnd); if (!period) return <p className="agency-note">Période historique sans durée standard vérifiable; aucun décompte approximatif n’est affiché.</p>; return <div className="agency-period" aria-label={period.active ? `Jour ${period.day} sur 30, ${period.daysRemaining} jour(s) restant(s)` : period.expired ? 'Abonnement expiré' : 'Période à venir'}><div><strong>{period.active ? `Jour ${period.day} sur 30` : period.expired ? 'Période expirée' : 'Période à venir'}</strong><span>{period.active ? `${period.daysRemaining} jour(s) restant(s)` : '30 jours d’accès'}</span></div><progress max="100" value={period.progress}/><small>Activation : {new Date(period.start).toLocaleString('fr-FR')} · Expiration : {new Date(period.end).toLocaleString('fr-FR')}</small></div>; })()}</section>
      <section className="agency-section"><div className="agency-section-heading"><div><small>ABONNEMENT</small><h2>Plans disponibles</h2></div><span>Tarifs publiés · AGENCY</span></div><p className="agency-note">Comparez prix, quota et durée avant de choisir. Votre nouvel accès commence dès confirmation du paiement et le quota non utilisé de l’ancienne période n’est pas reporté.</p>{plans.length ? <div className="agency-plans">{plans.map((plan) => <article className={selectedPlanKey === plan.key ? 'agency-plan-selected' : ''} key={plan.id}><h3>{plan.name}</h3><strong>{(plan.priceMinor / 100).toLocaleString('fr-FR')} {plan.currency} / 30 jours</strong><p>{plan.credits.toLocaleString('fr-FR')} invitations · 30 jours d’accès</p><button disabled={busy || current.role !== 'OWNER'} onClick={() => setSelectedPlanKey(plan.key)}>{selectedPlanKey === plan.key ? 'Plan sélectionné' : current.plan ? 'Choisir ce plan' : 'Sélectionner'}</button></article>)}</div> : <p className="agency-empty-inline">Aucun plan agence publié. Les offres apparaîtront ici dès qu’elles seront disponibles.</p>}{selectedPlanKey && (() => { const plan = plans.find(item => item.key === selectedPlanKey); if (!plan) return null; return <div className="agency-checkout-explainer"><h3>Votre abonnement · {plan.name}</h3><ul><li>{plan.credits.toLocaleString('fr-FR')} invitations</li><li>Valable exactement 30 jours</li><li>Démarre après confirmation du paiement</li><li>Quota non utilisé non reporté</li><li>{(plan.priceMinor / 100).toLocaleString('fr-FR')} {plan.currency}</li></ul><h4>Que se passe-t-il après le paiement ?</h4><ol><li>Le prestataire confirme le paiement.</li><li>L’abonnement est activé.</li><li>La période exacte de 30 jours démarre à cette confirmation.</li><li>Le quota complet devient disponible et l’ancien solde expire.</li></ol><button disabled={busy} onClick={() => void startCheckout()}>{busy ? 'Préparation…' : 'Continuer vers le paiement'}</button><button className="agency-cancel-selection" onClick={() => setSelectedPlanKey('')}>Annuler la sélection</button></div>; })()}</section>
      <div className="agency-columns"><section className="agency-section"><div className="agency-section-heading"><div><small>PORTefeuille CLIENT</small><h2>Clients</h2></div><span>{clients.length}</span></div>{loaded && clients.length === 0 ? <p className="agency-empty-inline">Aucun client dans ce workspace.</p> : clients.map((client) => <article className="agency-row" key={client.id}><strong>{client.name}</strong><span>{client.email ?? client.phone ?? 'Coordonnées non renseignées'}</span></article>)}{current.role !== 'MEMBER' && <form className="agency-form" onSubmit={createClient}><input name="name" required minLength={2} maxLength={120} placeholder="Nom du client"/><input name="email" type="email" placeholder="E-mail (optionnel)"/><input name="phone" placeholder="Téléphone (optionnel)"/><button disabled={busy}>Ajouter un client</button></form>}</section>
      <section className="agency-section"><div className="agency-section-heading"><div><small>COLLABORATION</small><h2>Membres</h2></div><span>{members.length}</span></div>{loaded && members.length === 0 ? <p className="agency-empty-inline">Aucun membre visible.</p> : members.map((member) => <article className="agency-row" key={member.id}><strong>{member.subject}</strong><span>{member.role} · {member.status}</span>{(current.role === 'OWNER' || current.role === 'ADMIN' && member.role === 'MEMBER') && member.role !== 'OWNER' && <span className="agency-member-actions"><select aria-label={`Rôle de ${member.subject}`} value={member.role} disabled={busy} onChange={(event) => void updateMember(member, { role: event.target.value })}><option value="MEMBER">MEMBER</option><option value="ADMIN">ADMIN</option></select><button disabled={busy} onClick={() => void updateMember(member, { status: member.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE' })}>{member.status === 'ACTIVE' ? 'Suspendre' : 'Réactiver'}</button><button disabled={busy} onClick={() => { if (window.confirm(`Retirer ${member.subject} de cette agence ?`)) void updateMember(member, { status: 'REMOVED' }); }}>Retirer</button></span>}</article>)}{(current.role === 'OWNER' || current.role === 'ADMIN') && <form className="agency-form" onSubmit={createMember}><input name="subject" required maxLength={255} placeholder="Identifiant de compte Keycloak"/><select name="role"><option value="MEMBER">Membre</option>{current.role === 'OWNER' && <option value="ADMIN">Administrateur</option>}</select><button disabled={busy}>Ajouter un membre</button></form>}</section></div>
      <section className="agency-section"><div className="agency-section-heading"><div><small>PRODUCTION</small><h2>Événements</h2></div><span>{events.length}</span></div>{loaded && events.length === 0 ? <p className="agency-empty-inline">Aucun événement lié à un client.</p> : events.map((item) => <article className="agency-row" key={item.id}><strong><a href={`/events/${item.id}`}>{item.name}</a></strong><span>{item.eventType} · {item.status}</span></article>)}{clients.length > 0 && <form className="agency-form agency-event-form" onSubmit={createEvent}><input name="name" required minLength={2} maxLength={120} placeholder="Nom de l’événement"/><select name="clientId" required defaultValue=""><option value="" disabled>Client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select><select name="eventType"><option value="WEDDING">Mariage</option><option value="BIRTHDAY">Anniversaire</option><option value="CONFERENCE">Conférence</option><option value="OTHER">Autre</option></select><button disabled={busy}>Créer un événement client</button></form>}</section>
      <button className="agency-refresh" onClick={() => void refresh().catch((error) => setMessage(error.message))} disabled={busy}>Actualiser les données</button>
    </>}
  </section>;
}
